**Import Libraries**

In [ ]:
import pandas as pd
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use("seaborn-v0_8")

In [ ]:
users = pd.read_csv("users.csv")
photos = pd.read_csv("photos.csv")
likes = pd.read_csv("likes.csv")
comments = pd.read_csv("comments.csv")
tags = pd.read_csv("tags.csv")
photo_tags = pd.read_csv("photo_tags.csv")
follows = pd.read_csv("follows.csv")

**Clean Columns Name**

In [ ]:
users.columns = users.columns.str.strip()
photos.columns = photos.columns.str.strip()
likes.columns = likes.columns.str.strip()
comments.columns = comments.columns.str.strip()

**Basic Overview**

In [ ]:
print("Total Users:", users['id'].nunique())
print("Total Photos:", photos['id'].nunique())
print("Total Likes:", likes.shape[0])
print("Total Comments:", comments.shape[0])

Total Users: 100
Total Photos: 257
Total Likes: 8782
Total Comments: 7488

**Calculate Likes Per Photo**

In [ ]:
likes_count = likes.groupby("photo").size().reset_index(name="likes_count")
likes_count.head()

   photo  likes_count
0      1           25
1      2           36
2      3           38
3      4           38
4      5           31

In [ ]:
comments.columns

Index(['id', 'comment', 'User  id', 'Photo id', 'created Timestamp',
       'posted date', 'emoji used', 'Hashtags used count'],
      dtype='object')

**Calculate Comments Per Photo**

In [ ]:
comments_count = comments.groupby("Photo id").size().reset_index(name="comments_count")
comments_count.head()

   Photo id  comments_count
0         1              25
1         2              31
2         3              27
3         4              32
4         5              27

In [ ]:
print(comments_count.columns)

Index(['Photo id', 'comments_count'], dtype='object')

**Merge Engagement Data**

In [1]:
import pandas as pd

# Load dataset
users = pd.read_csv("users.csv")
photos = pd.read_csv("photos.csv")
likes = pd.read_csv("likes.csv")
comments = pd.read_csv("comments.csv")

# Clean column names
users.columns = users.columns.str.strip().str.lower().str.replace(" ", "_")
photos.columns = photos.columns.str.strip().str.lower().str.replace(" ", "_")
likes.columns = likes.columns.str.strip().str.lower().str.replace(" ", "_")
comments.columns = comments.columns.str.strip().str.lower().str.replace(" ", "_")

# Create likes count
likes_count = likes.groupby("photo").size().reset_index(name="likes_count")

# Create comments count
comments_count = comments.groupby("photo_id").size().reset_index(name="comments_count")

# Merge data
photo_engagement = photos.merge(
    likes_count,
    left_on="id",
    right_on="photo",
    how="left"
)

photo_engagement = photo_engagement.merge(
    comments_count,
    left_on="id",
    right_on="photo_id",
    how="left"
)

# Fill missing values
photo_engagement['likes_count'] = photo_engagement['likes_count'].fillna(0)
photo_engagement['comments_count'] = photo_engagement['comments_count'].fillna(0)

photo_engagement['total_engagement'] = (
    photo_engagement['likes_count'] + photo_engagement['comments_count']
)

photo_engagement.head()

,id,image_link,user_id,created_dat,insta_filter_used,photo_type,photo,likes_count,photo_id,comments_count,total_engagement
0,1,http://elijah.biz,1,13-04-2023 08:04,yes,photo,1,25,1,25,50
1,2,https://shanon.org,1,13-04-2023 08:04,no,photo,2,36,2,31,67
2,3,http://vicky.biz,1,13-04-2023 08:04,no,photo,3,38,3,27,65
3,4,http://oleta.net,1,13-04-2023 08:04,no,photo,4,38,4,32,70
4,5,https://jennings.biz,1,13-04-2023 08:04,yes,photo,5,31,5,27,58

In [3]:
photo_engagement.head()

,id,image_link,user_id,created_dat,insta_filter_used,photo_type,photo,likes_count,photo_id,comments_count,total_engagement
0,1,http://elijah.biz,1,13-04-2023 08:04,yes,photo,1,25,1,25,50
1,2,https://shanon.org,1,13-04-2023 08:04,no,photo,2,36,2,31,67
2,3,http://vicky.biz,1,13-04-2023 08:04,no,photo,3,38,3,27,65
3,4,http://oleta.net,1,13-04-2023 08:04,no,photo,4,38,4,32,70
4,5,https://jennings.biz,1,13-04-2023 08:04,yes,photo,5,31,5,27,58